## 3.13 Developing Procedures — Exercises

[Source lesson and criteria](https://pages.opencodingsociety.com/python/developing-procedures/2026)

Completed exercises, predictions, runnable solutions, and recorded execution results follow. Each Python cell includes its own setup so it can run independently in the published runner.


## Exercise 1 — Meaningful names and decomposition
Instead of do_step or mystery_function, prepare_and_bake_dessert communicates its purpose. Helpers separate measuring, mixing, and baking so one step can be tested or changed without rewriting the sequence. Prediction: measure two cups, mix flour/sugar/eggs, then bake at 350°F for 25 minutes.


In [34]:
# CODE_RUNNER: 2026-10-07-developing-procedures-hw exercise 3
def measure_flour(cups):
    return f"Measure {cups} cups of flour."
def mix_ingredients():
    return "Mix flour, sugar, and eggs."
def bake_dessert(temperature, minutes):
    return f"Bake at {temperature} F for {minutes} minutes."
def prepare_and_bake_dessert(cups=2, temperature=350, minutes=25):
    """Return the ordered recipe instructions for the chosen quantities."""
    if cups <= 0 or temperature <= 0 or minutes <= 0:
        raise ValueError("Recipe quantities must be positive")
    return [measure_flour(cups), mix_ingredients(), bake_dessert(temperature,minutes)]
procedure_name = "prepare_and_bake_dessert"
procedures = {"prepare_and_bake_dessert":prepare_and_bake_dessert}
for instruction in procedures[procedure_name]():
    print(instruction)
assert measure_flour(2) == "Measure 2 cups of flour."
assert mix_ingredients() == "Mix flour, sugar, and eggs."
assert bake_dessert(350,25) == "Bake at 350 F for 25 minutes."
assert len(prepare_and_bake_dessert()) == 3
print("Helper and composition tests passed.")


Measure 2 cups of flour.
Mix flour, sugar, and eggs.
Bake at 350 F for 25 minutes.
Helper and composition tests passed.


### Recorded execution result

```text
Measure 2 cups of flour.
Mix flour, sugar, and eggs.
Bake at 350 F for 25 minutes.
Helper and composition tests passed.
```


## Exercise 2 — Java conversion and visibility
The public recipe method is the caller-facing interface. Private helpers hide implementation details; main can call the public method, but another class cannot directly call the private helpers. static allows these methods to run without constructing an object.

```java
public class DessertRobot {
    private static void measureFlour(int cups) {
        System.out.println("Measure " + cups + " cups of flour.");
    }
    private static void mixIngredients() {
        System.out.println("Mix flour, sugar, and eggs.");
    }
    private static void bakeDessert(int temperature, int minutes) {
        System.out.println("Bake at " + temperature + " F for " + minutes + " minutes.");
    }
    public static void prepareAndBakeDessert() {
        measureFlour(2);
        mixIngredients();
        bakeDessert(350, 25);
    }
    public static void main(String[] args) {
        prepareAndBakeDessert();
    }
}
```
Save as DessertRobot.java; compile with `javac DessertRobot.java` and run with `java DessertRobot`. The expected three output lines match the Python recipe.


## Exercise 3 — Refactor a long procedure
The monolithic and decomposed forms below return identical steps for two parameter sets. Decomposition makes helper behavior independently testable and exposes parameters rather than burying constants. Validation rejects impossible quantities instead of generating misleading instructions.


In [35]:
# CODE_RUNNER: 2026-10-07-developing-procedures-hw exercise 6
def recipe_monolith(cups, temperature, minutes):
    if cups <= 0 or temperature <= 0 or minutes <= 0:
        raise ValueError("Recipe quantities must be positive")
    return [f"Measure {cups} cups of flour.", "Mix flour, sugar, and eggs.",
            f"Bake at {temperature} F for {minutes} minutes."]
def measure_flour(cups):
    return f"Measure {cups} cups of flour."
def mix_ingredients():
    return "Mix flour, sugar, and eggs."
def bake_dessert(temperature, minutes):
    return f"Bake at {temperature} F for {minutes} minutes."
def recipe_decomposed(cups, temperature, minutes):
    if cups <= 0 or temperature <= 0 or minutes <= 0:
        raise ValueError("Recipe quantities must be positive")
    return [measure_flour(cups), mix_ingredients(), bake_dessert(temperature,minutes)]
for args in [(2,350,25),(3,325,30)]:
    assert recipe_monolith(*args) == recipe_decomposed(*args)
    print(args, recipe_decomposed(*args))
try:
    recipe_decomposed(0,350,25)
    raise AssertionError("Expected ValueError")
except ValueError:
    print("Invalid quantity correctly rejected.")


(2, 350, 25) ['Measure 2 cups of flour.', 'Mix flour, sugar, and eggs.', 'Bake at 350 F for 25 minutes.']
(3, 325, 30) ['Measure 3 cups of flour.', 'Mix flour, sugar, and eggs.', 'Bake at 325 F for 30 minutes.']
Invalid quantity correctly rejected.


### Recorded execution result

```text
(2, 350, 25) ['Measure 2 cups of flour.', 'Mix flour, sugar, and eggs.', 'Bake at 350 F for 25 minutes.']
(3, 325, 30) ['Measure 3 cups of flour.', 'Mix flour, sugar, and eggs.', 'Bake at 325 F for 30 minutes.']
Invalid quantity correctly rejected.
```


## Reflection and completion evidence
Descriptive names identify intent; parameters support reuse; procedures group a logical task; decomposition isolates changes and tests. Return values make tests easier than checking screen text alone. The three suggested activities—renaming, Java conversion/public-private explanation, and refactoring—are all included. This lesson does not supply a separate scored homework rubric or MCQ, so no quiz result is invented.
